# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Frederick Huang # this is what you'll see in browser tab when it's loaded onto a website.
url: "https://huangfrederick.github.io" # url name
baseurl: ""  # leave this blank for now unless you want to have subproject sites stemming from the URL

og_image: /assets/img/profile-pic.jpg # this is the repository source for where the profile picture on the landing page is pulled from.
google_analytics: "UA-121636368-3"

header:
  pages:
    - name: Home
      slug: /
    - name: CV
    - name: Work
    - name: Presentations
    - name: Teaching
    #- name: Blog

footer:
  show_powered_by: true
  contact:
    - type: email
      name: Email
      value: frederickhuang1@gmail.com
  follow:
    #- type: twitter
      #name: Twitter
      #link: http://twitter.com/YourTwitterUsername
      #username: "@YourTwitterUsername"
    #- type: facebook
      #name: Facebook
      #link: http://facebook.com/YourFacebookUsername
    - type: linkedin
      name: LinkedIn
      link: http://linkedin.com/in/frederick-huang-003846205
    - type: github
      name: GitHub
      link: http://github.com/huangfrederick

# Build settings
markdown: kramdown
sass:
    style: :compressed
plugins:
  - jekyll-feed

# Excluded items
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - feed.xml
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Used for defeating caching
version: 1
